backend:
  name: git-gateway
  branch: master

media_folder: static/uploads
public_folder: /uploads

collections:
  - name: thought
    label: Thought Leadership
    folder: src/pages/thought
    create: true
    slug: "{{slug}}"
    editor:
      preview: false    
    fields:
      - {label: Template Key, name: templateKey, widget: hidden, default: thought-post}
      - {label: Post Title, name: title, widget: string}
      - {label: URL, name: url, hint: 'ex: www.linkedin.com/pulse/example-post-title', widget: string}
      - {label: Post Author, name: author, widget: string}
      - {label: Publish Date, name: date, widget: datetime}
      - {label: Post Image, name: image, widget: image, hint: ''}

  - name: coaches
    label: Coaches
    editor:
      preview: false        
    files:
      - file: src/pages/coaches/index.md
        label: Coaches
        name: coaches
        fields:
          - {label: Template Key, name: templateKey, widget: hidden, default: coaches-page }
          - {label: Page Title, name: title, widget: text }
          - label: Coaches
            label_singular: Coach
            name: coachList
            widget: list
            fields:
              - {label: Name, name: coachName, widget: string, hint: 'Name must be unique'}
              - {label: Professional Title, name: jobTitle, widget: string, hint: 'Limit 75 characters', pattern: ['^.{0,75}$', 'Limit 75 characters']}
              - {label: Photo, name: photo, widget: image}
              - {label: Bio, name: bio, widget: markdown, buttons: [bold, italic, link, bulleted-list, numbered-list, quote, heading-two]}
              - {label: Tags, name: tags, widget: list}
              - label: Links
                name: links
                widget: object
                fields:
                  - {label: Website, name: website, widget: string, hint: 'Website URL (ex: www.mysite.com)', required: false, default: '' }
                  - {label: LinkedIn, name: linkedin, widget: string, hint: 'LinkedIn ID (found at the end of your LinkedIn profile URL)', pattern: ['^[a-zA-Z0-9_]{1,50}$', 'Invalid LinkedIn Username'], required: false, default: '' }
                  - {label: Twitter, name: twitter, widget: string, hint: 'Twitter Handle (do not include "@" symbol)', pattern: ['^[a-zA-Z0-9_]{1,15}$', 'Invalid Twitter Username'], required: false, default: '' }
                  - {label: Facebook, name: facebook, widget: string, hint: 'Facebook ID (found at the end of your Facebook profile URL)', pattern: ['^[a-zA-Z0-9_]{1,50}$', 'Invalid Facebook Username'], required: false, default: '' }
                  - {label: Instagram, name: instagram, widget: string, hint: 'Instagram Handle (do not include "@" symbol)', pattern: ['^[a-zA-Z0-9_]{1,30}$', 'Invalid Instagram Username'], required: false, default: '' }

  - name: pages
    label: Pages
    editor:
      preview: false      
    files:
      - file: src/pages/index.md
        label: Home
        name: home
        fields:
          - {label: Template Key, name: templateKey, widget: hidden, default: home-page}
          - label: Intro
            name: intro
            widget: object
            fields: 
              - {label: Intro Text, name: text, widget: text}
              - {label: Link Text, name: linkText, widget: string}
          - label: Coaches
            name: coaches
            widget: object
            fields: 
              - {label: Section Heading, name: headline, widget: string}
              - {label: Text, name: text, widget: text}
          - label: Consultancy
            name: consultancy
            widget: object
            fields:
              - {label: Section Heading, name: headline, widget: string}
              - {label: Text, name: text, widget: text}
              - {label: Link Text, name: linkText, widget: string}
          - label: Education
            name: education
            widget: object
            fields:
              - {label: Section Heading, name: headline, widget: string}
              - {label: Text, name: text, widget: text}
              - {label: Link Text, name: linkText, widget: string}
              - {label: Link URL, name: url, widget: string}
              - {label: Image, name: image, widget: image}
          - label: Institute
            name: institute
            widget: object
            fields:
              - {label: Section Heading, name: headline, widget: string}
              - {label: Text, name: text, widget: text}
              - {label: Link Text, name: linkText, widget: string}
              - {label: Link URL, name: url, widget: string}              

      - file: src/pages/about/index.md
        label: About
        name: about  
        fields:
          - {label: Template Key, name: templateKey, widget: hidden, default: about-page}
          - {label: Title, name: title, widget: string}
          - {label: Lede, name: lede, widget: text}
          - label: Video
            name: video
            widget: object
            fields: 
              - {label: Video URL, name: url, widget: string, hint: 'Example: https://www.youtube.com/watch?v=abcdefghijk123', default: '' }
              - {label: Title, name: title, widget: string, default: '', required: false }
              - {label: Description, name: description, widget: text, default: '', required: false }
          - {label: Body, name: body, widget: markdown, buttons: [bold, italic, link, bulleted-list, numbered-list, quote, heading-two]}

      - file: src/pages/services/index.md
        label: Services
        name: services  
        fields:
          - {label: Template Key, name: templateKey, widget: hidden, default: services-page}
          - {label: Title, name: title, widget: string}
          - {label: Lede, name: lede, widget: text}
          - label: Coaching Services
            name: coaching
            widget: object
            fields: 
              - {label: Description, name: description, widget: text}
          - label: Speaking Engagements
            name: speaking
            widget: object
            fields: 
              - {label: Description, name: description, widget: text}
          - label: Consulting Services
            name: consulting
            widget: object
            fields: 
              - {label: Description, name: description, widget: text}
              - label: Services
                name: servicesList
                widget: list
                fields:
                  - {label: Service Title, name: title, widget: string}
                  - {label: Service Description, name: description, widget: markdown, buttons: [bold, italic, link, bulleted-list, numbered-list, quote]}
                  - {label: Service Provider, name: provider, widget: string, required: false, default: ''}
                  - {label: Image, name: image, widget: image, hint: ''}
