backend:
  name: git-gateway
  branch: master

media_folder: static/uploads
public_folder: /uploads

collections:
  - name: thought
    label: Thought Leadership
    folder: src/pages/thought
    create: true
    slug: "{{slug}}"
    editor:
      preview: false    
    fields:
      - {label: Template Key, name: templateKey, widget: hidden, default: thought-post}
      - {label: Post Title, name: title, widget: string}
      - {label: URL, name: url, hint: 'ex: www.linkedin.com/pulse/example-post-title', widget: string}
      - {label: Post Author, name: author, widget: string}
      - {label: Publish Date, name: date, widget: datetime}
      - {label: Post Image, name: image, widget: image, hint: ''}

  - name: coaches
    label: Coaches
    files:
      - file: src/pages/coaches/index.md
        label: Coaches
        name: coaches
        editor:
          preview: false        
        fields:
          - {label: Template Key, name: templateKey, widget: hidden, default: coaches-page }
          - {label: Page Title, name: title, widget: text }
          - label: Coaches
            label_singular: Coach
            name: coachList
            widget: list
            fields:
              - {label: Name, name: coachName, widget: string}
              - {label: Professional Title, name: jobTitle, widget: string, pattern: ['^.{1,75}$', 'Limit 75 characters']}
              - {label: Photo, name: photo, widget: image}
              - {label: Bio, name: bio, widget: markdown, buttons: [bold, italic, link, bulleted-list, numbered-list, quote, heading-two]}
              - {label: Tags, name: tags, widget: list}
              - label: Links
                name: links
                widget: object
                fields:
                  - {label: Website, name: website, widget: string, hint: 'Website URL (ex: www.mysite.com)', default: "" }
                  - {label: LinkedIn, name: linkedin, widget: string, hint: 'LinkedIn ID (found at the end of your LinkedIn profile URL)', pattern: ['^[a-zA-Z0-9_]{1,50}$', 'Invalid LinkedIn Username'], default: "" }
                  - {label: Twitter, name: twitter, widget: string, hint: 'Twitter Handle (do not include "@" symbol)', pattern: ['^[a-zA-Z0-9_]{1,15}$', 'Invalid Twitter Username'], default: "" }
                  - {label: Facebook, name: facebook, widget: string, hint: 'Facebook ID (found at the end of your Facebook profile URL)', pattern: ['^[a-zA-Z0-9_]{1,50}$', 'Invalid Facebook Username'], default: "" }
                  - {label: Instagram, name: instagram, widget: string, hint: 'Instagram Handle (do not include "@" symbol)', pattern: ['^[a-zA-Z0-9_]{1,30}$', 'Invalid Instagram Username'], default: "" }

  - name: pages
    label: Pages
    files:
      - file: src/pages/index.md
        label: Home
        name: home
        editor:
          preview: false
        fields:
          - {label: Template Key, name: templateKey, widget: hidden, default: home-page}
          - label: Intro
            name: intro
            widget: object
            fields: 
              - {label: Intro Text, name: text, widget: text}
              - {label: Link Text, name: linkText, widget: string}
          - label: Coaches
            name: coaches
            widget: object
            fields: 
              - {label: Section Heading, name: headline, widget: string}
              - {label: Text, name: text, widget: text}
          - label: Consultancy
            name: consultancy
            widget: object
            fields:
              - {label: Section Heading, name: headline, widget: string}
              - {label: Text, name: text, widget: text}
              - {label: Link Text, name: linkText, widget: string}
          - label: Education
            name: education
            widget: object
            fields:
              - {label: Section Heading, name: headline, widget: string}
              - {label: Text, name: text, widget: text}
              - {label: Link Text, name: linkText, widget: string}
              - {label: Link URL, name: url, widget: string}
              - {label: Image, name: image, widget: image}
          - label: Institute
            name: institute
            widget: object
            fields:
              - {label: Section Heading, name: headline, widget: string}
              - {label: Text, name: text, widget: text}
              - {label: Link Text, name: linkText, widget: string}
              - {label: Link URL, name: url, widget: string}              

      - file: src/pages/about/index.md
        label: About
        name: about
        editor:
          preview: false        
        fields:
          - {label: Template Key, name: templateKey, widget: hidden, default: about-page}
          - {label: Title, name: title, widget: string}
          - {label: Lede, name: lede, widget: text}
          - label: Video
            name: video
            widget: object
            fields: 
              - {label: Video URL, name: url, widget: string, hint: 'Example: https://www.youtube.com/watch?v=abcdefghijk123', default: "" }
              - {label: Title, name: title, widget: string }
              - {label: Description, name: description, widget: text }
          - {label: Body, name: body, widget: markdown, buttons: [bold, italic, link, bulleted-list, numbered-list, quote, heading-two]}

      - file: src/pages/products/index.md
        label: Products Page
        name: products
        editor:
          preview: false        
        fields:
          - {label: Template Key, name: templateKey, widget: hidden, default: product-page}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Description, name: description, widget: string}
          - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
          - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
          - {label: Testimonials, name: testimonials, widget: list, fields: [{label: Quote, name: quote, widget: string}, {label: Author, name: author, widget: string}]}
          - {label: Full_image, name: full_image, widget: image}
          - {label: Pricing, name: pricing, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: string}, {label: Plans, name: plans, widget: list, fields: [{label: Plan, name: plan, widget: string}, {label: Price, name: price, widget: string}, {label: Description, name: description, widget: string}, {label: Items, name: items, widget: list}]}]}
